---
  - hosts: webserver
    become: true
    tasks:
      - name: Check webservers status
        command: service httpd status
        changed_when: false

      - name: Verify Apache is listening on 80
        wait_for: port=80 timeout=1
  
  - hosts: loadbalancer
    become: true
    tasks:
      - name: Check webservers status
        command: service httpd status
        changed_when: false

      - name: Verify Apache is listening on 80
        wait_for: port=80 timeout=1
  
  - hosts: local
    tasks:
      - name: Verify endpoint
        uri: url=http://{{server}} return_content=yes
        with_items: groups.loadbalancer
        register: lb_content
    
      - fail: msg='Failed to retrieve data'
        when: '"Hello world" not in item.content'
        with_items: '{{lb_content.results}}'