---
- hosts: loadbalancers
  become: true
  tasks:
    - service: name=httpd state=stopped
    - wait_for: port=80 state=drained

- hosts: webservers
  become: true
  tasks:
    - service: name=httpd state=stopped
    - wait_for: port=80 state=stopped

- hosts: webservers
  become: true
  tasks:
    - service: name=httpd state=started
    - wait_for: port=80 state=started # we can remove state=started because we use it above

- hosts: loadbalancers
  become: true
  tasks:
    - service: name=httpd state=started
    - wait_for: port=80 state=started