---
  - hosts: webservers
    become: true
    tasks:
      - name: Upload AngularJS App
        synchronize:
          src: ../site
          dest: /tmp
          rsync_opts:
            - "--exclude=node_modules"